### Create user
POST http://{{url_localhost}}/users
Content-Type: application/json

{
  "name": "Wilfredo Suarez",
  "email": "<email>",
  "password": "<secret>",
  "age": 35
}

### Login
POST http://{{url_localhost}}/users/login
Content-Type: application/json

{
"email": "<email>",
"password": "<secret>"
}

### Logout
POST http://{{url_localhost}}/users/logout
Content-Type: application/json
Authorization: Bearer {{token}}

### Logout
POST http://{{url_localhost}}/users/logout/all
Content-Type: application/json
Authorization: Bearer {{token}}


### Get users
GET http://{{url_localhost}}/users
Authorization: Bearer {{token}}